{
 "title": "MonitoringDashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "RAM Used",
   "type": "stat",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT (last(\"total\") - last(\"available\")) / 1024 / 1024 / 1024\nAS \"RAM utilisée (GiB)\"\nFROM \"mem\"\nWHERE $timeFilter"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 15, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "SELECT 100 * (mean(\"total\") - mean(\"available\")) / mean(\"total\")\nAS \"RAM utilisée (%)\"\nFROM \"mem\"\nWHERE $timeFilter\nGROUP BY time($__interval) fill(null)\n"
    }
   ]
  },
  {
   "title": "CPU Used",
   "type": "stat",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT 100 - mean(\"usage_idle\")\nFROM \"cpu\"\nWHERE $timeFilter AND \"cpu\"='cpu-total'\n"
    }
   ]
  },
  {
   "title": "CPU Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 15, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "SELECT 100 - mean(\"usage_idle\")\nFROM \"cpu\"\nWHERE $timeFilter AND \"cpu\"='cpu-total'\nGROUP BY time($__interval) fill(null)\n"
    }
   ]
  }
 ]
}